# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8a7118011c94d382b30b510aef74d9e0d4dccbe680521361439eca9c506b01fce2c04649babab16bb8318fa3b687f6eadcf20703281cc2248a414ad37b4ebb2

test:
  secret_key_base: 37b6f92be8db518f0a9805fb8122749fd61c3f866fe5870dd258179b05fcb7ee4b719cf3ac461a0a0249044a903c8a0d83c2e8e523633e36ed8d18672e165510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
